# Generated by Django 4.0.5 on 2022-06-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("action_id", models.AutoField(primary_key=True, serialize=False)),
                ("action_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("asset_id", models.AutoField(primary_key=True, serialize=False)),
                ("asset_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SOD",
            fields=[
                ("sod_code", models.AutoField(primary_key=True, serialize=False)),
                ("sod_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SODRules",
            fields=[
                ("sod_rule_id", models.AutoField(primary_key=True, serialize=False)),
                ("sod_rule_name", models.CharField(max_length=100)),
                ("sod_rule_description", models.CharField(max_length=100)),
                ("sod_rule_permission", models.BooleanField(default=True)),
                ("sod_rule_created_date", models.DateTimeField(auto_now_add=True)),
                ("sod_rule_updated_date", models.DateTimeField(auto_now=True)),
                (
                    "action_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.action"
                    ),
                ),
                (
                    "asset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "sod_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sod"
                    ),
                ),
            ],
        ),
    ]
