# Generated by Django 4.0.5 on 2022-06-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_application_action_created_at_action_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sodrules",
            old_name="sod_rule_create_by",
            new_name="sod_rule_created_by",
        ),
        migrations.RemoveField(
            model_name="sodrules",
            name="sod_rule_updated_by",
        ),
        migrations.RemoveField(
            model_name="sodrules",
            name="sod_rule_updated_date",
        ),
    ]
