# Generated by Django 4.0.5 on 2022-06-16 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_rename_sod_rule_create_by_sodrules_sod_rule_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionRules",
            fields=[
                (
                    "exception_rule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("exception_rule_name", models.CharField(max_length=100)),
                ("exception_rule_description", models.CharField(max_length=100)),
                ("exception_rule_approval_required", models.BooleanField(default=True)),
                (
                    "exception_rule_created_date",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="sodrules",
            old_name="sod_rule_permission",
            new_name="sod_rule_approval_required",
        ),
        migrations.AddField(
            model_name="action",
            name="application_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.application",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="application_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.application",
            ),
        ),
        migrations.DeleteModel(
            name="SODUser",
        ),
        migrations.AddField(
            model_name="exceptionrules",
            name="action_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.action"
            ),
        ),
        migrations.AddField(
            model_name="exceptionrules",
            name="application_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.application"
            ),
        ),
        migrations.AddField(
            model_name="exceptionrules",
            name="asset_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.asset"
            ),
        ),
        migrations.AddField(
            model_name="exceptionrules",
            name="exception_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exception_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exceptionrules",
            name="exception_rule_created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exception_rule_create_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
