# Generated by Django 4.0.5 on 2022-06-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_exceptionrules_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=100)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SodUser",
            fields=[
                ("soduser_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "application_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.application",
                    ),
                ),
                (
                    "sod_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sod"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.users"
                    ),
                ),
            ],
        ),
    ]
