# Generated by Django 4.0.5 on 2022-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_users_soduser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exceptionrules",
            options={"verbose_name": "Exception Rule"},
        ),
        migrations.AlterModelOptions(
            name="sodrules",
            options={"verbose_name": "SOD Rule"},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "User"},
        ),
        migrations.AddField(
            model_name="users",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
