# Generated by Django 4.0.5 on 2022-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_exceptionrules_options_alter_sodrules_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exceptionrules",
            name="exception_rule_approval_required",
        ),
        migrations.AddField(
            model_name="exceptionrules",
            name="exception_grand_type",
            field=models.CharField(
                choices=[
                    ("PG", "Permission Granted"),
                    ("PD", "Permission Denied"),
                    ("AR", "Approval Required"),
                ],
                default="PG",
                max_length=2,
            ),
        ),
    ]
