# Generated by Django 4.0.5 on 2022-06-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_exceptionrules_exception_rule_approval_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exceptionrules",
            name="exception_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exception_for",
                to="app.users",
            ),
        ),
        migrations.AlterField(
            model_name="exceptionrules",
            name="exception_grand_type",
            field=models.CharField(
                choices=[
                    ("PG", "PERMISSION_GRANTED"),
                    ("PD", "PERMISSION_DENIED"),
                    ("AR", "APPROVAL_REQUIRED"),
                ],
                default="PG",
                max_length=2,
            ),
        ),
    ]
