# Generated by Django 4.0.5 on 2022-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="folder_name",
            new_name="folder",
        ),
        migrations.AlterField(
            model_name="folder",
            name="folder_slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
