# Generated by Django 4.0.5 on 2022-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_folder_name_file_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_random_name",
            field=models.CharField(max_length=100),
        ),
    ]
