# Generated by Django 4.0.5 on 2022-06-17 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_file_file_random_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("RDM", "Request Direct Manager"),
                            ("RLM", "Request Location Manager"),
                        ],
                        default="RDM",
                        max_length=3,
                    ),
                ),
                ("notification_read", models.BooleanField(default=False)),
                (
                    "destination_folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.folder"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.file"
                    ),
                ),
                (
                    "notification_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
