# Generated by Django 4.0.5 on 2022-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="display",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TRDM", "Transfer Request Direct Manager"),
                    ("TRLM", "Transfer Request Location Manager"),
                    ("WRLM", "Write Request Location Manager"),
                    ("DLRM", "Delete Request Location Manager"),
                ],
                default="TRDM",
                max_length=4,
            ),
        ),
    ]
