export const GET_ACCESS = 'GET_ACCESS';
export const PERMISSION_GRANTED = 'PERMISSION_GRANTED';
export const PERMISSION_DENIED = 'PERMISSION_DENIED';
export const APPROVAL_REQUIRED = 'APPROVAL_REQUIRED';
